# 数据库的连接信息
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.94.184.216:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.184.216:8848
      config:
        enabled: false
  application:
    name: mall-product
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
server:
  port: 8040

